feat: UserProfile 페이지 제작
prgrms-fe-devcourse/FEDC4_Campers_Jaeho pull request #103
Opened 2023-09-16 08:52 UTC by Jeong-Taeho

## 이슈 번호

closes #81 

## 구현(수정) 내용

* UserProfile 페이지를 구현합니다.
* 마이페이지나 다른 유저 프로필 등 id 값으로 재사용 가능합니다.
* merge가 안된 상태로 브랜치를 파서 진행하느라 아직 재사용 가능한 컴포넌트를 가져다 사용하지 못해서 리팩토링 예정입니다.
* userId는 그냥 임의로 넣었습니다.
* 어떤 데이터를 쓸지 명확하지 않아 타입도 리팩토링 할 예정입니다.

## 스크린샷

![image](https://github.com/prgrms-fe-devcourse/FEDC4_Campers_Jaeho/assets/117630589/74d83a72-ed89-4646-8ee4-9d8cce904037)

## PR 포인트 및 궁금한 점

2023-09-16 09:06 UTC, perfumeplaylist reviewed
이 부분만 빨리 해주시면 바로 merge해도 좋을것 같습니다!

2023-09-16 09:06 UTC, perfumeplaylist commented on src/components/UserInfo.tsx
> +          </Text>
이번에 추상화한 TemperatureBar 컴포넌트 사용해보시면 좋을것 같아요!

2023-09-16 09:06 UTC, perfumeplaylist commented on src/components/UserInfo.tsx
> +        />
수정을 위해서 존재하는 input 컴포넌트 맞나용??!
맞으면 한번 상태로 보이도록 관리해보는게 좋을것 같아요!

2023-09-16 09:06 UTC, perfumeplaylist commented on src/components/UserInfo.tsx
> +          </Box>
이 부분은 반복되는 내용같은데 한번 추상화해보시는게 좋을것 같아요!
List로 묶는것도 좋을것 같네요!

2023-09-16 09:06 UTC, perfumeplaylist commented on src/apis/search.ts
> +    return { _id, fullName, email, posts, followers, followings };
```
 return data.map(
      ({ _id, fullName, isOnline, createdAt }: SearchUserParams) => 
        ({ _id, fullName, isOnline, createdAt })
    );
```
이렇게 선언했어야했는데 죄송합니다ㅠㅠㅠㅠ
오류 잡아주셔서 감사합니다! :)

2023-09-16 09:06 UTC, perfumeplaylist commented on src/apis/search.ts
> +    });
오 예상해서 데이터를 뽑아냈는데 테호님이 바로 잡아주셨군요! 👍 
감사합니다!

2023-09-16 09:45 UTC, Jeong-Taeho commented on src/apis/search.ts
> +    });
데이터가 쓰이는 부분이 예상이랑 많이 달라져서 예상하시기 힘들었을 것 같아요... 제가 한 부분들도 페이지를 만들면서 고쳐야 할 것 같습니다..

2023-09-16 09:46 UTC, Jeong-Taeho commented on src/components/UserInfo.tsx
> +        />
그 기존 input을 숨기고 input의 기능을 이미지나 아이콘을 눌러도 수정이 가능하도록 동기화를 시켜주어서 input을 숨겼습니다!!

2023-09-16 09:47 UTC, Jeong-Taeho commented on src/components/UserInfo.tsx
> +          </Box>
리팩토링 하면서 할까 했었는데 이건 엄청 간단한거니까 금방 해보겠습니다!!!

2023-09-16 11:27 UTC, sukvvon requested changes
> 리팩토링 하면서 할까 했었는데 이건 엄청 간단한거니까 금방 해보겠습니다!!!

금방 해보겠다고 하셔서 우선 `Request changes`로 리뷰하겠습니다!!

2023-09-16 11:27 UTC, sukvvon commented on src/components/UserInfo.tsx
> +    getUserData();
따로 빼서 `apis` 폴더 안에 파일 만드는건 어떨까요??

2023-09-16 11:27 UTC, sukvvon commented on src/components/UserInfo.tsx
> +      </Flex>
지금 혹은 나중에 Header(TopNavBar)로 뺴서 공통화하면 좋을 것 같아요!!

2023-09-16 12:05 UTC, Jeong-Taeho commented on src/components/UserInfo.tsx
> +      </Flex>
헤더가 페이지마다 바뀌는 부분이 많아서 어떻게 하는게 좋을지 상의해 본 다음 공통으로 같이 만들어야 될 것 같아요!!

2023-09-16 12:07 UTC, Jeong-Taeho commented on src/components/UserInfo.tsx
> +    getUserData();
searchUser 라는 axios 함수로 응답 받아서 상태들로 초기화해주는 부분인데 apis로 빼는게 맞을까요..?

2023-09-17 06:12 UTC, sukvvon approved these changes
LGTM!! 차차 리펙토링 하기로 하시죠!!

2023-09-17 06:12 UTC, merged