refactor: comment 사진에서 reacticon으로 변경
prgrms-fe-devcourse/FEDC4_Campers_Jaeho pull request #105
Opened 2023-09-17 07:05 UTC by euan-lee

## 이슈 번호

closes #104

## 구현(수정) 내용

*image에서 icon으로  변경

## 스크린샷

## PR 포인트 및 궁금한 점

2023-09-17 07:13 UTC, sukvvon requested changes

2023-09-17 07:13 UTC, sukvvon commented on src/components/common/Comment.tsx
> +            </Button>
팀 규칙 읽어주세요

2023-09-17 07:13 UTC, sukvvon commented
Comment 컴포넌트를 새로 생성하신건가요?

2023-09-18 03:57 UTC, perfumeplaylist reviewed
고생하셨어요 범진님 :)

2023-09-18 03:57 UTC, perfumeplaylist commented on src/components/common/Comment.tsx
> +        </Avatar>
제가 만든 이미지 컴포넌트를 사용하시면 기분이 좋을것 같아요! 😄

2023-09-18 03:57 UTC, perfumeplaylist commented on src/components/common/Comment.tsx
> +          </Button>
원석님이 만들어주신 버튼 컴포넌트 한번 활용해보시죠!

2023-09-18 08:16 UTC, sukvvon commented on src/components/common/Comment.tsx
> +          </Button>
정호님과 제가 만든 컴포넌트를 활용하면 기분이 좋을 것 같아요!!!

2023-09-18 16:06 UTC, Jeong-Taeho commented on src/pages/Detail.tsx
> +        <div>Loading...</div>
애니메이션 중에 로딩이 제일이라고 한번 예쁘게 같이 만들어보죠!!! 저도 이렇게 쓰고 있네요....

2023-09-19 06:30 UTC, closed without merging