Feat/#126 detail page
prgrms-fe-devcourse/FEDC4_Campers_Jaeho pull request #130
Opened 2023-09-19 09:22 UTC by euan-lee

## 이슈 번호

closes #126

## 구현(수정) 내용

*디테일 페이지구현
* main page와 detailPage 라우터  연결
* 날짜 형식 변환함수 구현
* comment component 생성
* detailpage 생성

## 스크린샷

## PR 포인트 및 궁금한 점

2023-09-19 09:46 UTC, sukvvon requested changes
고생하셨습니다!!

2023-09-19 09:46 UTC, sukvvon commented on src/utils/Date.ts
파일 이름을 formateData로 함수 이름과 통일하시는게 어떨까요?

2023-09-19 09:46 UTC, sukvvon commented on src/pages/Detail.tsx
> +                colorScheme="green"
없어도 될 것 같아요!! 한 번 `PrimaryButton` 확인해보시면 좋을 것 같아요!!
확인해보시고 수정 부탁드려요!!

2023-09-19 09:46 UTC, sukvvon commented on src/pages/Detail.tsx
> +                onClick={() => setIsDrawerOpen.on}
```suggestion
                onClick={setIsDrawerOpen.on}
```

2023-09-19 09:46 UTC, sukvvon commented on src/pages/Detail.tsx
> +                onClose={() => setIsDrawerOpen.off}
```suggestion
                onClose={setIsDrawerOpen.off}
```

2023-09-19 09:46 UTC, sukvvon commented on src/pages/Detail.tsx
> +            <Center bg="#green.400">
```suggestion
            <Center bg="green.400">
```

2023-09-19 09:46 UTC, sukvvon commented on src/pages/Detail.tsx
> +  useEffect(() => {
```suggestion
  const [isDrawerOpen, setIsDrawerOpen] = useBoolean();
  
  useEffect(() => {
```

줄 바꿈 해주시면 보기 편할 것 같아요!!

2023-09-19 09:46 UTC, sukvvon commented on src/pages/Detail.tsx
> +                  style={{ top: '20px' }}
신기하네요... 저 공부해야겠습니다... ㅠㅠ

2023-09-19 09:46 UTC, sukvvon commented on src/pages/Detail.tsx
> +    const fetchData = async () => {
```suggestion
    if (postId === undefined) return;
    
    const fetchData = async () => {
    
    줄바꿈 하면 편할 것 같아요!!
```

2023-09-20 02:43 UTC, perfumeplaylist reviewed
범진님 고생하셨습니다!
페이지 코드 수가 점점 줄어드는게 보이는게 노력이 많이하신게 느껴지고 있습니다 :)
화이팅!!!

2023-09-20 02:43 UTC, perfumeplaylist commented on src/components/ContentList.tsx
>                style={{ position: 'absolute', width: '100%', height: '100%' }}
제가 정의한 PrimaryLink 컴포넌트 한번 이용해주세용 ✌️

2023-09-20 02:43 UTC, perfumeplaylist commented on src/components/common/Comment.tsx
> +        </Avatar>
제가 정의한 아바타 컴포넌트 사용하면 더 코드가 줄어들것 같습니다!

2023-09-20 02:43 UTC, perfumeplaylist commented on src/components/common/Comment.tsx
> +        <Text fontSize="20px">{comment}</Text>
제가 정의한 Text 컴포넌트 한번 이용해 주세용!
저희가 닉네임 길이를 정해놓지 않아서 길어지만 ui/ux상으로 안좋아질것 같아서 제작했습니다!

2023-09-20 02:43 UTC, perfumeplaylist commented on src/components/common/Comment.tsx
> +            </Button>
원석님이 정의한 버튼 컴포넌트로 해결할수 있을것 같은데 어떠신가요??!

2023-09-20 02:43 UTC, perfumeplaylist commented on src/pages/Detail.tsx
> +    if (postId === undefined) return;
오 디테일 👍

2023-09-20 02:43 UTC, perfumeplaylist commented on src/pages/Detail.tsx
> +    []
라이브러리 이용하셨군요!
리펙토링때는 저희가 한번 구현해보죠! :)

2023-09-20 02:43 UTC, perfumeplaylist commented on src/pages/Detail.tsx
> +                    {formatDate(data.posterInfo.updatedAt)}
유틸로 정의하신거 너무 갬동... 👍

2023-09-20 02:43 UTC, perfumeplaylist commented on src/pages/Detail.tsx
> +                  <Text fontSize={50}>{data.posterInfo.title}</Text>
이것도 제가 정의한 텍스트 컴포넌트 이용해주시죠!

2023-09-20 02:43 UTC, perfumeplaylist commented on src/pages/Detail.tsx
> +                    />
갬동... 👍

2023-09-20 02:43 UTC, perfumeplaylist commented on src/pages/Detail.tsx
> +                      <Text fontSize={15}>{data.posterInfo.fullName}</Text>
이것도 텍스트 컴포넌트 사용하면 좋을것 같아요! :)

2023-09-20 02:43 UTC, perfumeplaylist commented on src/pages/Detail.tsx
> +              </Drawer>
리펙토링때는 이거를 컴포넌트로 분리하는게 더 좋아보이네요! :)
react-query 사용하실때 도움 많이 될것 같습니다!

2023-09-20 02:43 UTC, perfumeplaylist commented on src/utils/formateData.ts
이거는 위에 유틸함수랑 다른점이 뭔가용??!

2023-09-20 08:54 UTC, sukvvon requested changes

2023-09-20 08:54 UTC, sukvvon commented on src/utils/Date.ts
`Data.ts` 파일 삭제해주세요!!

2023-09-20 09:10 UTC, sukvvon approved these changes
LGTM!!

2023-09-20 09:10 UTC, merged