feat: 유저페이지에서 알림모달창 구현
prgrms-fe-devcourse/FEDC4_Campers_Jaeho pull request #142
Opened 2023-09-20 09:25 UTC by nsr1349

## 이슈 번호

closes #113

## 구현(수정) 내용

* userProfile 에 알림 리스트를 보여주는 모달창입니다
* 모달창을 눌렀을 때 뒤 화면에 옆으로 이동하는 버그가 존재합니다. (thema 파일의 maxW를 제거하면 일시적으로 해결이 되긴합니다.)

추가 필요한 기능 
* 해당 유저가 자신일 때만 알림, 에딧 아이콘을 보여줄까 합니다.
* 알림창을 누르면 관련페이지로 이동하는 기능을 추가하긴 해야합니다

아셔야할 부분
중요: 원래 userInfo 페이지에 기능을 추가하는 것이 맞았지만,
현재 userProfile 로 기능구현할 페이지가 변경 되었습니다 . 
따라서 userInfo 를 삭제처리하였습니다.

## 스크린샷

## PR 포인트 및 궁금한 점

2023-09-20 16:19 UTC, Jeong-Taeho commented on src/apis/Notification.ts
> +      headers: { Authorization: `Bearer ${token}` },
성래님!! instance 자체 생성할 때 이 부분이 되있는걸로 아는데 여기서도 해야 동작하나요??

2023-09-20 16:19 UTC, Jeong-Taeho commented on src/apis/Notification.ts
> +    console.error(error);
error처리는 여기서 axios 에러만 처리해주는게 좋다고 판단되서 고칠 수 있으면 고쳐주시면 감사하겠습니다!!

```suggestion
  } catch (error) {
  if(error instanceof AxiosError){
    console.error(error.message);
  }
```

이런 느낌이에요!!

2023-09-20 21:58 UTC, sukvvon requested changes
고생하셨습니다 성래님!!

2023-09-20 21:58 UTC, sukvvon commented on src/apis/Notification.ts
> +      headers: { Authorization: `Bearer ${token}` },
instance를 활용해서 바꿔주시면 좋을 것 같아요!!

2023-09-20 21:58 UTC, sukvvon commented on src/apis/Notification.ts
> +    console.error(error);
동의합니다!!

2023-09-20 21:58 UTC, sukvvon commented on src/pages/UserProfile.tsx
> +        <ModalContent margin="20px" overflow="hidden">
```suggestion
        <ModalContent m="20px" overflow="hidden">
```

2023-09-20 21:58 UTC, sukvvon commented on src/pages/UserProfile.tsx
> +          <Box flex="1"></Box>
```suggestion
          <Box flex={1}></Box>
```

2023-09-21 04:06 UTC, Jeong-Taeho commented on src/pages/UserProfile.tsx
> +      <Modal isOpen={isOpen} onClose={onClose}>
성래님 이거 모달 컴포넌트로 다른 파일에 생성해서 재사용하는 방식으로 가능할까요??

2023-09-21 16:23 UTC, Jeong-Taeho commented on src/pages/UserProfile.tsx
> +  ).data;
쿼리 훅 부분으로 빼보면서 리팩토링 해봐야겠네요!! 이 정의를 참고하겠습니다👍

2023-09-24 07:32 UTC, sukvvon approved these changes

2023-09-24 07:36 UTC, merged