feat: User Query 세분화 / react-query devtool 정의
prgrms-fe-devcourse/FEDC4_Campers_Jaeho pull request #180
Opened 2023-09-22 09:06 UTC by perfumeplaylist

## 이슈 번호

closes #179 

## 구현(수정) 내용

* User Query 세분화
* react-query devtool 정의

## 스크린샷

## PR 포인트 및 궁금한 점

2023-09-22 09:47 UTC, sukvvon requested changes
`apis` 파일을 제거하고 `hooks` 아래로 mutation, query 소문자로 해서 위치시키면 좋을 것 같아요!!

2023-09-22 13:14 UTC, sukvvon commented on src/main.tsx
> +import theme from './theme/index.ts';
```suggestion
import theme from './theme/';
```

이렇게 해도 작동이 될 것 같은데 한 번 확인해주실 수 있으실까요??

2023-09-23 08:30 UTC, Jeong-Taeho submitted a review, later dismissed
파일 구조 같은거는 나중에 리팩토링 하면 되니까 얼른 머지되면 좋을 것 같아요!!

2023-09-23 08:33 UTC, sukvvon commented
집에 가는대로 바로 머지하겠습니다!! 🙏

2023-09-23 10:13 UTC, perfumeplaylist commented
충돌은 해결했습니다! 한번 확인해 주십쇼!

2023-09-23 11:05 UTC, sukvvon approved these changes
LGTM!!

2023-09-23 11:05 UTC, merged