Feature/21 axios autoh
prgrms-fe-devcourse/FEDC4_Campers_Jaeho pull request #30
Opened 2023-09-09 13:42 UTC by perfumeplaylist

## 이슈 번호

closes #21

## 구현(수정) 내용

* 서버와 통신이 가능한 회원가입 로직 구현
* 서버와 통신이 가능한 인증에 관한 로직 구현
* 토큰 관리를 위해 localstorage 유틸함수 구현

## 스크린샷

## PR 포인트 및 궁금한 점

- localstorage 유틸 함수로 정의한 이유는 전역적으로 사용되기 때문에 커스텀으로 제작시 선언 시에만 특정 상태로 할당되어서 이 점때문에 유틸함수로 따로 정의 했습니다! 
- env는 저희 요청 주소에 포트번호 추가한거 입니다! 잊지마세요!

2023-09-09 13:43 UTC, sukvvon commented
제가 handle 할게요

2023-09-09 13:46 UTC, sukvvon requested changes
`.env`파일 안에 어떤 값들이 있는지 알려주는 `.env.example` 파일도 추가해주시면 감사하겠습니다!!

2023-09-09 13:47 UTC, euan-lee submitted a review, later dismissed
고생하셨습니다 저도 마저 구현해야 겠습니다..

2023-09-09 13:50 UTC, sukvvon commented
@euan-lee제가 request 요청 보낸거 확인하셨나요?
혹시 왜 approval 승인 하셨는지 알 수 있을까요?

2023-09-09 13:52 UTC, Jeong-Taeho commented on src/apis/auth.ts
> +}
타입에 사용되는 type이나 interface는 파스칼케이스로 작성하는게 정해진건 아니지만 규칙이라고 알고있어서 상관없을까요.?

2023-09-09 14:04 UTC, sukvvon approved these changes

2023-09-09 14:04 UTC, sukvvon commented on src/apis/auth.ts
> +}
```suggestion
interface SignupParams {
  email: string;
  fullName: string;
  password: string;
}
```
`interface`나 `type` 같은 경우 처음에 대문자로 해야하는 것으로 알고있습니다!! 변경 부탁드립니다!!
또한 SignupParams와 SignupParams 중에 어떤 것을 해야하는지 문맥적으로 고민이네요... 어떻게 생각하시나요??
@perfumeplaylist @Jeong-Taeho

2023-09-09 14:04 UTC, sukvvon commented on src/utils/storage.ts
> +export const getStorage = (key: string, defaultValue = '') => {
```suggestion
export const getLocalStorage = (key: string, defaultValue = '') => {
```

2023-09-09 14:04 UTC, sukvvon commented on src/utils/storage.ts
> +export const setStorage = (key: string, value: string) => {
```suggestion
export const setLocalStorage = (key: string, value: string) => {
```

2023-09-09 14:04 UTC, sukvvon commented on src/utils/storage.ts
> +export const removeStorage = (key: string) => {
```suggestion
export const removeLocalStorage = (key: string) => {
```
`localStorage`임을 명시해주는 것이 좋을 것 같습니다!

2023-09-09 14:04 UTC, sukvvon commented on src/apis/auth.ts
> +interface loginParams {
```suggestion
interface LoginParams {
```

2023-09-09 14:07 UTC, sukvvon approved these changes

2023-09-09 14:07 UTC, Jeong-Taeho commented on src/apis/auth.ts
> +}
지금 원석님이 suggestion 해주신 대로 바꾸면 좋을 것 같습니다!!

2023-09-09 14:08 UTC, sukvvon requested changes
실수입니다 🙏

2023-09-09 14:08 UTC, perfumeplaylist commented on src/apis/auth.ts
> +}
저도 이 부분은 같이 얘기하고 싶었습니다!
지금 코드를 더 생각해서 리펙토링을 할려고 생각하고 있어서 편하게 얘기해주시면 리펙토링때 참고하겠습니다!

2023-09-09 14:27 UTC, euan-lee commented
> @euan-lee제가 request 요청 보낸거 확인하셨나요? 혹시 왜 approval 승인 하셨는지 알 수 있을까요?

 확인 했습니다!

2023-09-09 14:36 UTC, sukvvon commented
지금 확인중입니다!!

2023-09-09 14:47 UTC, sukvvon requested changes

2023-09-09 14:47 UTC, sukvvon commented on src/apis/auth.ts
> +};
```suggestion
export const signup = async ({ email, fullName, password }: SignupParams) => {
  await axiosInterface.post('signup', {
    email,
    fullName,
    password,
  });
};
```
이런 식으로 [구조 분해 할당(객체)](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#%EA%B0%9D%EC%B2%B4_%EA%B5%AC%EC%A1%B0_%EB%B6%84%ED%95%B4)를 하면 좋을 것 같습니다!!
또한 의문인것은 `signup`에서 만약 email이 중복이면 에러를 api가 보내지 않나라는 생각을 해봅니다!!
`try catch`로 한 번 시도 해보시면 좋을 것 같습니다!!

2023-09-09 14:47 UTC, sukvvon commented on src/apis/auth.ts
> +    });
```suggestion
export const login = async ({ email, password }: LoginParams) => {
  try {
    const {
      data: { user, token },
    } = await axiosInterface.post('login', {
      email,
      password,
    });
```

2023-09-09 14:47 UTC, sukvvon commented on src/apis/axios.ts
> +    const storageValue = getLocalStorage('token', '');
```js
    const storageValue = getLocalStorage('token', '');
```

`storageValue`에 관해서 이름을 `storagedValue`, `token`, `item` 중 하나로 하면 명확할 것 같다는 생각이 듭니다!!
@perfumeplaylist @euan-lee @Jeong-Taeho @nsr1349 어떻게 생각하시나요?

2023-09-09 14:51 UTC, Jeong-Taeho commented on src/apis/axios.ts
> +    const storageValue = getLocalStorage('token', '');
저는 storedValue로 사용하는게 좋아보입니다!

2023-09-09 14:54 UTC, euan-lee commented on src/apis/axios.ts
> +    const storageValue = getLocalStorage('token', '');
storedvalue에 한표 던저보겠습니다. 좀더 직관적인것 같습니다

2023-09-09 14:54 UTC, euan-lee commented on src/apis/auth.ts
> +};
오 훨씬 보기 좋네요! 저도 작성시 참고 하겠습니다

2023-09-10 01:26 UTC, euan-lee submitted a review, later dismissed

2023-09-10 02:15 UTC, sukvvon approved these changes
고생하셨습니다!! 차후 리펙토링 하는것으로 하시죠!! 🙋🏻‍♂️

2023-09-10 02:16 UTC, merged

2023-09-10 02:59 UTC, euan-lee commented on src/apis/auth.ts
> +    token && setLocalStorage('token', token);
이거 토큰값을 암호화 ex)123u8213123ffh 해서 .env파일에 숨기는건 어떨까요??!! 다른분들 의견이 궁금하네요