feat: 포스트 생성 컴포넌트 구현
prgrms-fe-devcourse/FEDC4_Campers_Jaeho pull request #59
Opened 2023-09-13 08:18 UTC by Jeong-Taeho

## 이슈 번호

closes #36 

## 구현(수정) 내용

* 포스트 생성 컴포넌트 구현
* 포스트 생성 api 코드 간단하게 수정

## 스크린샷

## PR 포인트 및 궁금한 점

2023-09-14 08:10 UTC, perfumeplaylist reviewed
다 같이 리펙토링을 통해서 컴포넌트 분리 해보시죠!

2023-09-14 08:10 UTC, perfumeplaylist commented on src/components/CreatePost.tsx
> +  };
react-router 이용하셔서 구현해보시면 좋을것 같습니다!

2023-09-14 08:10 UTC, perfumeplaylist commented on src/components/CreatePost.tsx
> +    formData.append('channelId', '64fbfdabe8468d1ed414e307');
채널 아이디는 env파일로~~!

2023-09-14 08:10 UTC, perfumeplaylist commented on src/components/CreatePost.tsx
> +    }
`setSelectedImages((prev)=>[...prev,...newFilesArray])`
전에 값을 활용하신다면 이런식으로 작성해보시죠!

2023-09-14 08:10 UTC, perfumeplaylist commented on src/components/CreatePost.tsx
> +  };
ref를 활용해서 해보시는건 어떠신가요??!
document.querySelector는 전체 document를 탐색한다는 단점이 있어서

2023-09-14 08:11 UTC, sukvvon requested changes

2023-09-14 08:11 UTC, sukvvon commented on src/components/CreatePost.tsx
> +  const [loadedMap, setLoadedMap] = useState<boolean>(false);
`useBoolean` 훅을 써보면 어떨까요??

2023-09-14 08:11 UTC, sukvvon commented on src/components/CreatePost.tsx
> +      <form onSubmit={handleSubmit(onSubmit)}>
```suggestion
      <Stack as="form" spacing={4} onSubmit={handleSubmit(onSubmit)}>
```

이렇게 수정해도 작동이 될 것 같아요!!

2023-09-14 08:11 UTC, sukvvon commented on src/components/CreatePost.tsx
> +      </form>
```suggestion
      </Stack>
```

2023-09-14 13:22 UTC, sukvvon requested changes

2023-09-14 13:22 UTC, sukvvon commented on src/components/CreatePost.tsx
> +}
```suggestion
type FileImage = {
  id: string;
  file: File;
}

type NewPostData =  {
  title: string;
  image: FileImage[];
  channelId: string;
}
```

`interface`가 아닌 `type`으로 수정해주시고 상관은 없지만 문맥상 흐름을 위해 `FileImage`를 먼저 선언해주시면 좋을 것 같아요!!

2023-09-15 04:51 UTC, perfumeplaylist approved these changes
나중에 리펙토링때 컴포넌트 분리만 하면 될것 같군요! 👍 
제가 merge하겠습니다!

2023-09-15 05:23 UTC, sukvvon approved these changes
LGTM!!

2023-09-15 05:23 UTC, merged