feature: MoreText 컴포넌트 생성
prgrms-fe-devcourse/FEDC4_Campers_Jaeho pull request #71
Opened 2023-09-14 03:27 UTC by perfumeplaylist

## 이슈 번호

closes #67 

## 구현(수정) 내용

* 단일기능(더보기 기능)이 가능한 컴포넌트 생성
* props으로 보고싶은 text, 처음에 보고싶은 height을 입력받는다.

## 스크린샷

## PR 포인트 및 궁금한 점

2023-09-14 13:33 UTC, sukvvon requested changes

2023-09-14 13:33 UTC, sukvvon commented on src/components/Post/MoreText.tsx
> +  const [toggle, setToggle] = useState(false);
`useBoolean`으로 바꿔주시면 좋을 것 같아요!!

2023-09-14 13:33 UTC, sukvvon commented on src/components/common/TemperatureBar.tsx
> +      <Text color="green.400" fontSize="3">
```suggestion
      <Text color="green.400" fontSize={3}>
```

2023-09-14 13:33 UTC, sukvvon commented on src/components/common/TemperatureBar.tsx
> +        marginRight="1"
```suggestion
        borderRadius={4}
        marginRight={1}
```

2023-09-14 13:33 UTC, sukvvon commented on src/components/common/TemperatureBar.tsx
> +};
```suggestion
type TemperatureBarProps = ProgressProps & {
  size?: string;
};
```

`ProgressProps`안에 `value` 속성이 있어서 type에 넣지 않아도 될 것 같습니다!!

2023-09-14 13:33 UTC, sukvvon commented on src/components/Post/MoreText.tsx
> +      <Button size="sm" onClick={handleToggle} mt="1rem">
```suggestion
      <Button size="sm" onClick={handleToggle} mt={4}>
```
chakra에서 정의된 값으로 바꿀 수 있을 것 같습니다!!

2023-09-15 04:26 UTC, perfumeplaylist commented on src/components/Post/MoreText.tsx
> +  const [toggle, setToggle] = useState(false);
넵 알겠습니다~!

2023-09-15 05:36 UTC, sukvvon requested changes

2023-09-15 05:36 UTC, sukvvon commented on src/components/Post/MoreText.tsx
> +    setToggle((prev) => !prev);
```suggestion
    setisToggled.toggle();
```
`useBoolean`훅 안에서 제공된 함수들을 사용해주세요!!

2023-09-15 05:36 UTC, sukvvon commented on src/components/Post/MoreText.tsx
> +  const [toggle, setToggle] = useBoolean(false);
```suggestion
  const [istoggled, setIsToggled] = useBoolean();
```
```suggestion
  const [toggle, setToggle] = useBoolean(false);
```
`useBoolean` 기본값은 `false`입니다!!
또한 이름은 직관적으로 위와 같이 변경하는게 나을 것 같아요!!

2023-09-15 05:36 UTC, sukvvon commented on src/components/common/TemperatureBar.tsx
> +        colorScheme="green"
```suggestion
        color="green.400"
```
이렇게 해도 적용이 되나요? 
적용이 되면 colorScheme는 color= green.500, green.400을 기본으로 하는게 좋을 것 같아요!!

2023-09-15 07:20 UTC, sukvvon requested changes

2023-09-15 07:20 UTC, sukvvon commented on src/components/Post/MoreText.tsx
> +  const [isToggle, setIsToggled] = useBoolean();
```suggestion
  const [isToggled, setIsToggled] = useBoolean();
```

2023-09-15 07:20 UTC, sukvvon commented on src/components/Post/MoreText.tsx
> +      <Collapse {...props} startingHeight={maxHeight} in={isToggle}>
```suggestion
      <Collapse {...props} startingHeight={maxHeight} in={isToggled}>
```

2023-09-16 06:47 UTC, sukvvon submitted a review, later dismissed
👍👍

2023-09-16 06:48 UTC, sukvvon approved these changes
👍👍

2023-09-16 06:49 UTC, sukvvon approved these changes
👍👍

2023-09-16 06:50 UTC, merged