refactor: import 순, 타입지정 등 피드백 반영
prgrms-fe-devcourse/FEDC4_Campers_Jaeho pull request #77
Opened 2023-09-14 07:04 UTC by nsr1349

## 이슈 번호

closes #74

## 구현(수정) 내용

* import 순서 변경
* 변수명과 타입명 수정
* useEffect 기본 함수 제거
* main 에 원래 있음 안되는 바텀 네브바 뻈어요

## 스크린샷

## PR 포인트 및 궁금한 점

2023-09-14 14:52 UTC, sukvvon requested changes

2023-09-14 14:52 UTC, sukvvon commented on src/components/ContentList.tsx
> +type Props = {
```suggestion
type ContentListProps = {
```
이런식으로 `type` 이름을 변경하는 것이 더 직관적일 것 같아요!!

2023-09-14 14:52 UTC, sukvvon commented on src/components/ContentList.tsx
> +const ContentList = ({ contents }: Props) => {
```suggestion
const ContentList = ({ contents, spacing, borderRadius }: ContentListProps) => {
```

2023-09-14 14:52 UTC, sukvvon commented on src/components/MainPageContent.tsx
> +    moreContent();
```suggestion
    getMoreContents();
```
`getMoreContents`나 `fetchMoreContents`로 함수 이름을 바꾸는 것이 좋을 것 같습니다!! 어떻게 생각하시나요??
@perfumeplaylist @Jeong-Taeho @euan-lee 어떻게 생각하시나요!

2023-09-14 14:52 UTC, sukvvon commented on src/components/MainPageContent.tsx
> +      <Flex flexDir="column" pos="relative" p="15 15 50 15">
```suggestion
      <Flex flexDir="column" pos="relative" p="15 15 50 15">
```
`p="15 15 50 15"` 이 코드가 동작하지 않는 것 같아 보입니다!! 확인 부탁드립니다!

2023-09-14 14:52 UTC, sukvvon commented on src/components/MainPageContent.tsx
> +        <Box w="100%" p="20" textAlign="center">
```suggestion
        <Box w="100%" p={20} textAlign="center">
```

20으로 하신 의도가 20px이신 것 같은데 20과 20px은 다른 단위입니다.
<img width="527" alt="image" src="https://github.com/prgrms-fe-devcourse/FEDC4_Campers_Jaeho/assets/66409882/f1995bfa-6f4b-447f-8237-38b1e09b829a">
공식문서를 다시 한 번 확인해보시는게 좋을 것 같아요

2023-09-14 14:52 UTC, sukvvon commented on src/components/ContentList.tsx
> +  borderRadius?: string;
spacing, borderRadius 값을 받아오는데 이미 컴포넌트 안에 지정이 되어있는 것 같습니다.
삭제를 하던지 값을 넣던지 통일해주시면 감사하겠습니다!!

2023-09-15 06:21 UTC, euan-lee commented on src/components/MainPageContent.tsx
> +    moreContent();
fetchMoreContents가 보기 좋지않나 싶네요

2023-09-15 06:21 UTC, Jeong-Taeho commented on src/components/MainPageContent.tsx
> +    moreContent();
`getMoroContents`가 좋아보입니다!!

2023-09-15 06:21 UTC, sukvvon commented on src/components/MainPageContent.tsx
> +    moreContent();
getMoreContents`로 가는게 나을 것 같습니다!!

2023-09-15 09:04 UTC, sukvvon requested changes

2023-09-15 09:04 UTC, sukvvon commented on src/components/ContentList.tsx
> +          bgImg={image ? image : 'https://via.placeholder.com/150'}
```suggestion
          bgImg={image || 'https://via.placeholder.com/150'}
```
이런 식으로 수정하면 좋을 것 같아요!!

2023-09-15 09:04 UTC, sukvvon commented on src/components/Main/MainPageContent.tsx
> +  const contentCount = useRef<number>(0);
```suggestion
  const contentCount = useRef(0);
```
타입 추론이 되어서 제거하셔도 될 것 같아요!!

2023-09-15 09:04 UTC, sukvvon commented on src/components/Main/MainPageContent.tsx
> +    moreContent();
수정이 아직 안되었습니다!!

2023-09-15 16:11 UTC, sukvvon requested changes

2023-09-15 16:11 UTC, sukvvon commented on src/pages/Main.tsx
> +            boxSize="8"
```suggestion
            boxSize={8}
```

괄호 제거를 왜 하신거죠? 다시 넣어주시길 부탁드립니다... 😂

2023-09-16 14:53 UTC, Jeong-Taeho reviewed
얼른 수정하고 merge 시키는게 좋을 것 같습니다!! 메인에서 연결되어야 하는 부분이 많아서요!!

2023-09-16 17:56 UTC, sukvvon commented
@Jeong-Taeho 좋습니다! 일단 머지시키겠습니다!

2023-09-16 18:05 UTC, sukvvon approved these changes
👍

2023-09-16 18:05 UTC, merged

2023-09-16 18:10 UTC, sukvvon commented
```js
import MainPageContent from '../components/Main/MainPageContent';
```

@Jeong-Taeho @euan-lee  @perfumeplaylist 

제가 경로 수정을 잘못했네요.
이렇게 수정해서 사용해주시기 바랍니다!! 🙋🏻‍♂️