feat: detailpage 레이아웃 구현
prgrms-fe-devcourse/FEDC4_Campers_Jaeho pull request #94
Opened 2023-09-15 08:40 UTC by euan-lee

## 이슈 번호

closes #91

## 구현(수정) 내용

* 페이지 레이아웃 구현

## 스크린샷

## PR 포인트 및 궁금한 점

2023-09-15 15:44 UTC, sukvvon requested changes

2023-09-15 15:44 UTC, sukvvon commented on src/images/more.png
이미지를 `react-icons`를 통해서 수정해주세요!!

2023-09-18 03:55 UTC, perfumeplaylist reviewed
범진님 고생하셨습니다!
리펙토링하실때 한번 고려해보세요!

2023-09-18 03:55 UTC, perfumeplaylist commented on src/pages/Detail.tsx
> +                      day: 'numeric',
따로 유틸함수로 빼주시는게 좋아보이는데 어떻게 생각하시나요??!

2023-09-18 03:55 UTC, perfumeplaylist commented on src/pages/Detail.tsx
> +              </Drawer>
지금 디테일 페이지에 기능이 많이 몰려 있는것 같은데 범진님은 어떻게 생각하시나요??!
많이 몰려있다면 나중에 리펙토링때 따로 컴포넌트로 빼주시면 좋을것 같아요!!
:)

2023-09-18 03:55 UTC, perfumeplaylist commented on src/pages/Detail.tsx
> +              </Button>
원석님이 만들어주신 버튼 한번 활용해보시죠!!! :)

2023-09-18 03:55 UTC, perfumeplaylist commented on src/pages/Detail.tsx
> +                    </Avatar>
제가 만든 아바타 이미지 컴포넌트 사용해주시면 너무 기분이 좋을것 같군요! 😄

2023-09-18 03:55 UTC, perfumeplaylist commented on src/pages/Detail.tsx
> +                />
👍

2023-09-18 06:01 UTC, euan-lee commented on src/pages/Detail.tsx
> +              </Drawer>
네! 리펙토링 한번 해야할것같네용!

2023-09-18 08:04 UTC, sukvvon requested changes

2023-09-18 08:04 UTC, sukvvon commented on src/App.tsx
> +        <Route path={ROUTES.DETAIL} element={<Detail />} />
NotFound보다 위로 위치를 변경해주세요!

2023-09-18 08:04 UTC, sukvvon commented on src/pages/Detail.tsx
> +  const [isDrawerOpen, setIsDrawerOpen] = useState(false);
`useBoolean`으로 바꿀 수 있을 것 같아요!!

2023-09-18 16:02 UTC, Jeong-Taeho commented on src/pages/Detail.tsx
> +};
이거 타입 제가 지금 명세서에서 다 받아와서 apis에 타입 파일로 만들어 놔서 PR할 예정이니까 리팩토링 하면서 가져다 쓰시죠👍

2023-09-19 06:30 UTC, closed without merging