feat: comment create axios구현
prgrms-fe-devcourse/FEDC4_Campers_Jaeho pull request #96
Opened 2023-09-15 09:10 UTC by euan-lee

## 이슈 번호

closes #95

## 구현(수정) 내용

* axios comment create 함수
* axios comment delete 함수

## 스크린샷

## PR 포인트 및 궁금한 점

2023-09-16 05:50 UTC, sukvvon requested changes

2023-09-16 05:50 UTC, sukvvon commented on src/apis/comment.ts
> +export const sendComment = async ({ comment, postId }: CommentData) => {
```suggestion
export const createComment = async ({ comment, postId }: CommentData) => {
```
`createComment`는 어떤가요??

2023-09-18 03:43 UTC, perfumeplaylist commented on src/apis/comment.ts
> +export const sendComment = async ({ comment, postId }: CommentData) => {
저도 그것만 제외하고 괜찮은것 같습니다!

2023-09-18 16:05 UTC, Jeong-Taeho commented on src/apis/comment.ts
> +  }
```suggestion
  } catch (error) {
    if(error instanceof AxiosError){
       console.error(error.message)
    } else if (error instanceof Error) {
      console.error(error.message)
    } else {
      console.error(error)
    }
  }
```

저는 이런식으로 처리해볼까 하고 있는데 어떤가요..? 이거 그냥 여기서 하드코딩 한거라 suggestion 하면 큰일납니다 허허🤣

2023-09-20 02:28 UTC, perfumeplaylist reviewed
고생하셨습니다 범진님!
리뷰 한번 확인부탁드려용!

2023-09-20 02:28 UTC, perfumeplaylist commented on src/apis/comment.ts
> +    alert('success');
axios로직은 데이터만 출력하는게 좋은것 같습니다!
react-query에서 성공시 메세지 출력하는거를 생각하시는게 더 좋을것 같습니다 :)

2023-09-20 02:28 UTC, perfumeplaylist commented on src/apis/comment.ts
> +    } else {
이런 부분은 타입 단언으로 처리하는건 어떠신가요??!

2023-09-20 16:16 UTC, Jeong-Taeho commented on src/apis/comment.ts
> +    console.error(error);
정호님 말씀대로 axios 관련된 오류만 처리해주시면 query에서 다른 에러도 깔끔하게 처리해 보겠습니다😊

2023-09-24 05:37 UTC, Jeong-Taeho approved these changes
LGTM!!

2023-09-24 05:41 UTC, Jeong-Taeho commented
@sukvvon 이거 저희한테는 머지가 안되네요.. 머지 시키고 범진님과 수정하면서 디테일 페이지 해보겠습니다!!

2023-09-24 05:43 UTC, sukvvon commented
@Jeong-Taeho 제가 request require 걸어놔서 그렇습니다!! 제가 확인하고 머지하겠습니다!!

2023-09-24 05:45 UTC, sukvvon approved these changes

2023-09-24 05:45 UTC, merged